# _config.yml for Jekyll site

# Site settings
# These settings are used to personalize your new site.
# They can be accessed in the templates via {{ site.title }}, {{ site.email }}, etc.

title: "过去一年"
email: "your-email@example.com"
description: "Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
# These settings affect how your site is built and processed.

theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# The following items will not be processed by default.
# Any item listed here will be automatically added to the internal "default list".
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
